/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.geb.groovy.conflict;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
